eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
server:
  port: 8771
spring:
  application:
    name: eshop-price-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/eshop
    username: root
    password: haojiayou@
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitadmin
    password: haojiayou@