eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
server:
  port: 8767
spring:
  application:
    name: zuul-server
zuul:
  routes:
    say-hello-service:
      path: /say-hello-service/**
      serviceId: say-hello-service
    greeting-service:
      path: /greeting-service/**
      serviceId: greeting-service