eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: say-hello-service
  zipkin:
    base-url: http:/127.0.0.1:9411

